name: mice_eeg_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anaconda-anon-usage=0.4.4=py312hd6b623d_100
  - appnope=0.1.4=pyhd8ed1ab_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - boltons=23.0.0=py312hca03da5_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py312h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.7.4=hf0a4a13_0
  - certifi=2024.8.30=py312hca03da5_0
  - cffi=1.16.0=py312h80987f9_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - conda=24.7.1=py312hca03da5_0
  - conda-content-trust=0.2.0=py312hca03da5_1
  - conda-libmamba-solver=24.1.0=pyhd3eb1b0_0
  - conda-package-handling=2.3.0=py312hca03da5_0
  - conda-package-streaming=0.10.0=py312hca03da5_0
  - contourpy=1.2.0=py312h48ca7d4_0
  - cryptography=42.0.5=py312hd4332d6_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py312h313beb8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distro=1.9.0=py312hca03da5_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h313beb8_0
  - filelock=3.13.1=py312hca03da5_0
  - fmt=9.1.0=h48ca7d4_1
  - fonttools=4.51.0=py312h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - frozendict=2.4.2=py312hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py312hca03da5_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.26.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py312hca03da5_0
  - jpeg=9e=h80987f9_3
  - jsonpatch=1.33=py312hca03da5_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py312h81bd7bf_0
  - kiwisolver=1.4.4=py312h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libarchive=3.6.2=h62fee54_3
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcurl=8.7.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h80987f9_3
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libmamba=1.5.8=haeffa04_2
  - libmambapy=1.5.8=py312h1c5506f_2
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libsodium=1.0.18=h27ca646_1
  - libsolv=0.7.24=h514c7bf_1
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.0=h3e2b118_0
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.10.4=h0b34f26_2
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py312h80987f9_0
  - matplotlib=3.9.2=py312hca03da5_0
  - matplotlib-base=3.9.2=py312h2df2da3_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - menuinst=2.1.1=py312hca03da5_0
  - mpmath=1.3.0=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.2.1=py312hca03da5_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.3.1=hfb2fe0b_2
  - packaging=23.2=py312hca03da5_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h80987f9_0
  - pip=24.0=py312hca03da5_0
  - platformdirs=3.10.0=py312hca03da5_0
  - pluggy=1.0.0=py312hca03da5_1
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py312h7e5086c_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h80987f9_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.2=hdf0ec26_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python.app=3=py312h80987f9_0
  - python_abi=3.12=4_cp312
  - pytorch=2.4.1=py3.12_0
  - pyyaml=6.0.1=py312h80987f9_0
  - pyzmq=25.1.1=py312h2105c20_2
  - readline=8.2=h1a28f6b_0
  - reproc=14.2.4=h313beb8_2
  - reproc-cpp=14.2.4=h313beb8_2
  - requests=2.32.2=py312hca03da5_0
  - ruamel.yaml=0.17.21=py312h80987f9_0
  - setuptools=69.5.1=py312hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.13.2=py312hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - torchvision=0.19.1=py312_cpu
  - tornado=6.4.1=py312h7e5086c_0
  - tqdm=4.66.4=py312h989b03a_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - truststore=0.8.0=py312hca03da5_0
  - typing_extensions=4.12.2=pyha770c72_0
  - unicodedata2=15.1.0=py312h80987f9_0
  - urllib3=2.2.2=py312hca03da5_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py312hca03da5_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yaml-cpp=0.8.0=h313beb8_1
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.2.13=hfb2fe0b_6
  - zstandard=0.22.0=py312h1a4646a_0
  - zstd=1.5.5=hd90d995_2
  - pip:
      - agate==1.9.1
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - altair==5.4.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - attrs==24.2.0
      - babel==2.16.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - click==8.1.7
      - colorama==0.4.6
      - daff==1.3.46
      - daproli==0.22
      - dbt-adapters==1.7.0
      - dbt-common==1.10.0
      - dbt-core==1.8.7
      - dbt-extractor==0.5.1
      - dbt-postgres==1.8.2
      - dbt-semantic-interfaces==0.5.1
      - deepdiff==7.0.1
      - einops==0.8.0
      - fastjsonschema==2.20.0
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.25.2
      - importlib-metadata==6.11.0
      - ipywidgets==8.1.5
      - isodate==0.6.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - julius==0.2.7
      - jupyterlab-widgets==3.0.13
      - lazy-loader==0.4
      - leather==0.4.0
      - lightning==2.4.0
      - lightning-utilities==0.11.7
      - llvmlite==0.43.0
      - logbook==1.5.3
      - markdown-it-py==3.0.0
      - mashumaro==3.13.1
      - mat73==0.65
      - mdurl==0.1.2
      - minimal-snowplow-tracker==0.0.2
      - mne==1.8.0
      - more-itertools==10.5.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - narwhals==1.8.2
      - nbformat==5.10.4
      - neurokit2==0.2.10
      - numba==0.60.0
      - opencv-python==4.10.0.84
      - ordered-set==4.1.0
      - pandas==2.2.3
      - parsedatetime==2.6
      - pathspec==0.12.1
      - patsy==0.5.6
      - plotly==5.24.1
      - polars==1.7.1
      - pooch==1.8.2
      - protobuf==4.25.5
      - psycopg2-binary==2.9.9
      - pyarrow==17.0.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydeck==0.9.1
      - pyjwt==2.9.0
      - python-slugify==8.0.4
      - pytimeparse==1.1.8
      - pytorch-lightning==2.4.0
      - pytz==2024.2
      - pywavelets==1.9.0
      - referencing==0.35.1
      - rich==13.8.1
      - rpds-py==0.20.0
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlparse==0.5.1
      - statsmodels==0.14.4
      - stqdm==0.0.5
      - streamlit==1.38.0
      - tenacity==8.5.0
      - tensorboardx==2.6.4
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - timm==1.0.10
      - toml==0.10.2
      - torchaudio==2.4.1
      - torchmetrics==1.4.2
      - tzdata==2024.1
      - watchdog==5.0.2
      - watermark==2.5.0
      - widgetsnbextension==4.0.13
      - yarl==1.11.1
prefix: /opt/miniconda3/envs/mice_eeg_env
