name: mice_eeg_env
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-anon-usage=0.4.4
  - appnope=0.1.4
  - archspec=0.2.3
  - asttokens=2.4.1
  - blas=1.0
  - boltons=23.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.4
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.2.2
  - conda=24.7.1
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - contourpy=1.2.0
  - cryptography=42.0.5
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - distro=1.9.0
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - filelock=3.13.1
  - fmt=9.1.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - icu=73.1
  - idna=3.7
  - importlib_metadata=8.2.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libarchive=3.6.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.7.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.4
  # - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - menuinst=2.1.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=23.2
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0
  # - python.app=3
  - python_abi=3.12
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.2
  - ruamel.yaml=0.17.21
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - truststore=0.8.0
  - typing_extensions=4.12.2
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - agate==1.9.1
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - altair==6.0.0
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - attrs==24.2.0
      - babel==2.16.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - click==8.1.7
      - colorama==0.4.6
      - daff==1.3.46
      - daproli==0.22
      - dbt-adapters==1.7.0
      - dbt-common==1.10.0
      - dbt-core==1.8.7
      - dbt-extractor==0.5.1
      - dbt-postgres==1.8.2
      - dbt-semantic-interfaces==0.5.1
      - deepdiff==7.0.1
      - einops==0.8.0
      - fastjsonschema==2.20.0
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.25.2
      - importlib-metadata==6.11.0
      - ipywidgets==8.1.5
      - isodate==0.6.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - julius==0.2.7
      - jupyterlab-widgets==3.0.13
      - lazy-loader==0.4
      - leather==0.4.0
      - lightning==2.6.0
      - lightning-utilities==0.11.7
      - llvmlite==0.43.0
      - logbook==1.5.3
      - markdown-it-py==3.0.0
      - mashumaro==3.13.1
      - mat73==0.65
      - mdurl==0.1.2
      - minimal-snowplow-tracker==0.0.2
      - mne==1.8.0
      - more-itertools==10.5.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - narwhals==2.14.0
      - nbformat==5.10.4
      - neurokit2==0.2.10
      - numba==0.60.0
      - opencv-python==4.10.0.84
      - ordered-set==4.1.0
      - pandas==2.2.3
      - parsedatetime==2.6
      - pathspec==0.12.1
      - patsy==0.5.6
      - plotly==5.24.1
      - polars==1.7.1
      - pooch==1.8.2
      - protobuf==4.25.5
      - psycopg2-binary==2.9.9
      - pyarrow==17.0.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydeck==0.9.1
      - pyjwt==2.9.0
      - python-slugify==8.0.4
      - pytimeparse==1.1.8
      - pytorch-lightning==2.4.0
      - pytz==2024.2
      - pywavelets==1.9.0
      - referencing==0.35.1
      - rich==13.8.1
      - rpds-py==0.20.0
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - smmap==5.0.1
      - sniffio==1.3.1
      - sqlparse==0.5.1
      - statsmodels==0.14.4
      - stqdm==0.0.5
      - streamlit==1.52.2
      - sympy==1.14.0
      - tenacity==8.5.0
      - tensorboardx==2.6.4
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - timm==1.0.10
      - toml==0.10.2
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchmetrics==1.4.2
      - torchvision==0.24.1
      - tzdata==2024.1
      - watchdog==6.0.0
      - watermark==2.5.0
      - widgetsnbextension==4.0.13
      - yarl==1.11.1
# prefix: /opt/miniconda3/envs/mice_eeg_env
